Window.SetBackgroundTopColor(0.07, 0.075, 0.13);
Window.SetBackgroundBottomColor(0.14, 0.10, 0.25);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.x = Window.GetWidth()  / 2 - logo.image.GetWidth()  / 2;
logo.y = Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 40;
logo.sprite.SetPosition(logo.x, logo.y, 10);

// Простая полоса прогресса под логотипом
progress_box.width  = 240;
progress_box.height = 4;
progress_box.x = Window.GetWidth() / 2 - progress_box.width / 2;
progress_box.y = logo.y + logo.image.GetHeight() + 40;

fun refresh_callback() {
    progress = Plymouth.GetBootProgress();
    bar.image = Image.Text(" ", 1, 1, 1);
}

Plymouth.SetRefreshFunction(refresh_callback);
