# Последовательность экранов установщика ApOS.
# Пользователь всегда сначала загружается в LIVE-сессию (обычный рабочий стол),
# пробует систему, и уже оттуда запускает установщик — это и есть "попробовать
# ОС до установки", как в Mint/Ubuntu.

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id: rootfs
  module: unpackfs
  config: unpackfs.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - packagechooser
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - bootloader
  - grubcfg
  - umount
- show:
  - finished

branding: apos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end-process: false
